#!/bin/bash

lua.exe ./build_elua.lua board=EK-TM4C123GXL #boot=luarpc

if [ $? == 0 ]
then
    arm-none-eabi-objcopy -O binary ./elua_lua_ek-tm4c123gxl.elf ./payload.hex
    cp ./elua_lua_ek-tm4c123gxl.elf payload.bin
    lmflash -v ./payload.hex
fi
